{
  "formatVersion": "1.1",
  "component": {
    "group": "com.easytier",
    "module": "easytier-android-jni",
    "version": "2.6.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "easytier-android-jni-2.6.4.aar",
          "url": "easytier-android-jni-2.6.4.aar",
          "size": 32946889,
          "sha512": "11ffae93b847ff5358b5fb93393ab717788d7115a4aa359f6acfee471fb92a3f31bfaabd79dfdf65030a7255c3e7acc757d8aa1af46214bc4361024b8f1d9f1f",
          "sha256": "35d5cd5b29ce77d7e585fa858efcdf7cbf6b1d9b1a4663268577055dc3031ced",
          "sha1": "61abd2a6b5c68dd5aacf1f87c6bbddb3118ddb63",
          "md5": "7c95045a2e5f089e4b97be24897fba19"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "easytier-android-jni-2.6.4.aar",
          "url": "easytier-android-jni-2.6.4.aar",
          "size": 32946889,
          "sha512": "11ffae93b847ff5358b5fb93393ab717788d7115a4aa359f6acfee471fb92a3f31bfaabd79dfdf65030a7255c3e7acc757d8aa1af46214bc4361024b8f1d9f1f",
          "sha256": "35d5cd5b29ce77d7e585fa858efcdf7cbf6b1d9b1a4663268577055dc3031ced",
          "sha1": "61abd2a6b5c68dd5aacf1f87c6bbddb3118ddb63",
          "md5": "7c95045a2e5f089e4b97be24897fba19"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "easytier-android-jni-2.6.4-sources.jar",
          "url": "easytier-android-jni-2.6.4-sources.jar",
          "size": 1707,
          "sha512": "dd76d96676a1940d8a4922e8d949357c1e09bb9446c22b60838990fbfd39fc4bff35524476be2100bc6f4a91f2cddc2b7982d03579fd28815afa7a1e502e3c2a",
          "sha256": "6921b5450a3e2cd2d5d2eabd4910971d8eac9aa315215c7c1ea316e4519ea400",
          "sha1": "305ce7b606691bb8deb399362e0380f16cc4d35e",
          "md5": "7f04c98416fb4fbbeef1c7a38f426e76"
        }
      ]
    }
  ]
}
