{
  "formatVersion": "1.1",
  "component": {
    "group": "com.easytier",
    "module": "easytier-jni",
    "version": "2.6.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "easytier-jni-2.6.4.aar",
          "url": "easytier-jni-2.6.4.aar",
          "size": 32946583,
          "sha512": "ed09e24eeb43a612fcaebedad3cbc58689eb955ef45e717cf41dd2376443bbf1718641244d3c50852326a4f9121eedf74ad957268ff40b17d6681de5e245e8c3",
          "sha256": "4cac7e6ce61e5cca9ac378e2ed0f1b7a0d791d8073b9d75e6635ebe137344618",
          "sha1": "3f0e2f445afee32865250585a6e57ea41eb65081",
          "md5": "dec5aa7a05481583062991c8afb032cd"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "easytier-jni-2.6.4.aar",
          "url": "easytier-jni-2.6.4.aar",
          "size": 32946583,
          "sha512": "ed09e24eeb43a612fcaebedad3cbc58689eb955ef45e717cf41dd2376443bbf1718641244d3c50852326a4f9121eedf74ad957268ff40b17d6681de5e245e8c3",
          "sha256": "4cac7e6ce61e5cca9ac378e2ed0f1b7a0d791d8073b9d75e6635ebe137344618",
          "sha1": "3f0e2f445afee32865250585a6e57ea41eb65081",
          "md5": "dec5aa7a05481583062991c8afb032cd"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "easytier-jni-2.6.4-sources.jar",
          "url": "easytier-jni-2.6.4-sources.jar",
          "size": 1707,
          "sha512": "dd76d96676a1940d8a4922e8d949357c1e09bb9446c22b60838990fbfd39fc4bff35524476be2100bc6f4a91f2cddc2b7982d03579fd28815afa7a1e502e3c2a",
          "sha256": "6921b5450a3e2cd2d5d2eabd4910971d8eac9aa315215c7c1ea316e4519ea400",
          "sha1": "305ce7b606691bb8deb399362e0380f16cc4d35e",
          "md5": "7f04c98416fb4fbbeef1c7a38f426e76"
        }
      ]
    }
  ]
}
