{
  "formatVersion": "1.1",
  "component": {
    "group": "com.easytier",
    "module": "easytier-jni",
    "version": "2.6.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "easytier-jni-2.6.4.aar",
          "url": "easytier-jni-2.6.4.aar",
          "size": 37706482,
          "sha512": "e370090fded01ceb3134ae7894cf5cb6bbf5b16fb9869cc081e566a49fdf15f75e304229506af969e92f6ec458388dcba72cf43ab6316b26bcb95f9f8908000b",
          "sha256": "ff5fc58bc4b16df208b8cb40d80028b4577d3cc1444d510f8d95cb7b0419227b",
          "sha1": "f853a3cdd5a77dd6fae3dd332fc04a46b818861c",
          "md5": "2d76d54962403365adf1746883b070b7"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "easytier-jni-2.6.4.aar",
          "url": "easytier-jni-2.6.4.aar",
          "size": 37706482,
          "sha512": "e370090fded01ceb3134ae7894cf5cb6bbf5b16fb9869cc081e566a49fdf15f75e304229506af969e92f6ec458388dcba72cf43ab6316b26bcb95f9f8908000b",
          "sha256": "ff5fc58bc4b16df208b8cb40d80028b4577d3cc1444d510f8d95cb7b0419227b",
          "sha1": "f853a3cdd5a77dd6fae3dd332fc04a46b818861c",
          "md5": "2d76d54962403365adf1746883b070b7"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "easytier-jni-2.6.4-sources.jar",
          "url": "easytier-jni-2.6.4-sources.jar",
          "size": 1713,
          "sha512": "7fffcc5af4847dfcad05c9b62955d23687ea55f113a901ee518cf38b1aed745bd6ed9a69b0db8cc8ae8c6ab29710a670421f3d81ee5031b5a7b54c8fddd5fe47",
          "sha256": "d54b5252b154a58c71db0efb45a3b8b114b51c04703cb3288c4e1828b4f4c709",
          "sha1": "03c176bfc19186660a8b141bd86453c4838a29f2",
          "md5": "5465f6275c472f22ae05d95fe6dd568f"
        }
      ]
    }
  ]
}
