{
  "formatVersion": "1.1",
  "component": {
    "group": "org.bluepowerrobotics",
    "module": "AIAPIConverter",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.alibaba",
          "module": "dashscope-sdk-java",
          "version": {
            "requires": "2.22.28"
          }
        },
        {
          "group": "com.openai",
          "module": "openai-java",
          "version": {
            "requires": "4.50.0"
          }
        },
        {
          "group": "com.anthropic",
          "module": "anthropic-java",
          "version": {
            "requires": "2.52.0"
          }
        },
        {
          "group": "com.google.genai",
          "module": "google-genai",
          "version": {
            "requires": "1.64.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.19.4"
          }
        }
      ],
      "files": [
        {
          "name": "AIAPIConverter-1.0.0.jar",
          "url": "AIAPIConverter-1.0.0.jar",
          "size": 155121,
          "sha512": "690a1eab45daa29bd4556750b098273025b83b3dd8fb5b2ebbc0910a7b152c5024ce2504081608cd7eb9e6136d95fbf17628f6d398bd5e9b84f56e24ba52aef8",
          "sha256": "4b0c1f30851d1c801b4f2c0636b0a134dccff4cf39199bb19138817945b54965",
          "sha1": "340d6130cb580652b6b430ee5474b1601b356ecc",
          "md5": "2b93045762cdf0b99bd7d14a11d40d76"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.alibaba",
          "module": "dashscope-sdk-java",
          "version": {
            "requires": "2.22.28"
          }
        },
        {
          "group": "com.openai",
          "module": "openai-java",
          "version": {
            "requires": "4.50.0"
          }
        },
        {
          "group": "com.anthropic",
          "module": "anthropic-java",
          "version": {
            "requires": "2.52.0"
          }
        },
        {
          "group": "com.google.genai",
          "module": "google-genai",
          "version": {
            "requires": "1.64.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.19.4"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-nop",
          "version": {
            "requires": "2.0.18"
          }
        }
      ],
      "files": [
        {
          "name": "AIAPIConverter-1.0.0.jar",
          "url": "AIAPIConverter-1.0.0.jar",
          "size": 155121,
          "sha512": "690a1eab45daa29bd4556750b098273025b83b3dd8fb5b2ebbc0910a7b152c5024ce2504081608cd7eb9e6136d95fbf17628f6d398bd5e9b84f56e24ba52aef8",
          "sha256": "4b0c1f30851d1c801b4f2c0636b0a134dccff4cf39199bb19138817945b54965",
          "sha1": "340d6130cb580652b6b430ee5474b1601b356ecc",
          "md5": "2b93045762cdf0b99bd7d14a11d40d76"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "AIAPIConverter-1.0.0-sources.jar",
          "url": "AIAPIConverter-1.0.0-sources.jar",
          "size": 65584,
          "sha512": "e9e3113447c8574de48269fd89a050a0e8385828e39ac55a06e7efc053f6d6d1cda260b6509b930bd50d4520156cb30c93be06778eb67bc8688cd009060560be",
          "sha256": "8ed7d8256498e68e3327199cf36f7c44d794f5d4c4d162640ad9879a383fab7d",
          "sha1": "ec6921386ee290d0cc3e597e1ff9a31f85dbb94e",
          "md5": "eac2321b76bec40533b6e06de589d487"
        }
      ]
    }
  ]
}
